export const mockEnhancedRecommendations = [
  {
    id: 'rec-1',
    title: 'Add Missing Meta Description',
    description: 'Your page is missing a meta description, which appears in search results and influences click-through rates.',
    impact: {
      seoScore: 8,
      userExperience: 6,
      conversionPotential: 9,
      implementationEffort: 'low' as const,
      timeToImplement: 3,
    },
    implementation: {
      autoFixAvailable: true,
      codeSnippet: {
        before: '<!-- No meta description -->',
        after: '<meta name="description" content="Discover our premium SEO tools that help you rank higher in search results. Get detailed analysis, competitor insights, and actionable recommendations.">',
        language: 'html',
      },
      stepByStep: [
        'Open your HTML file or CMS editor',
        'Locate the <head> section',
        'Add the meta description tag after the title',
        'Write compelling copy that includes your main keyword',
        'Keep it between 150-160 characters for optimal display',
      ],
      tools: ['HTML Editor', 'CMS', 'Character Counter'],
      documentation: ['https://developers.google.com/search/docs/appearance/snippet'],
    },
    businessCase: {
      estimatedTrafficIncrease: '15-25%',
      competitorComparison: 'Appears in search results snippets',
      roi: '3 minutes work = better click-through rates',
    },
    quickWin: true,
    category: 'onpage',
    priority: 'high' as const,
  },
  {
    id: 'rec-2',
    title: 'Optimize Images with Alt Text',
    description: '12 images are missing alt text, which hurts accessibility and SEO. Alt text helps search engines understand your images.',
    impact: {
      seoScore: 6,
      userExperience: 9,
      conversionPotential: 5,
      implementationEffort: 'low' as const,
      timeToImplement: 8,
    },
    implementation: {
      autoFixAvailable: true,
      codeSnippet: {
        before: '<img src="hero-image.jpg" class="banner">',
        after: '<img src="hero-image.jpg" alt="Professional SEO team analyzing website performance data" class="banner">',
        language: 'html',
      },
      stepByStep: [
        'Identify all images without alt attributes',
        'For each image, write descriptive alt text',
        'Include relevant keywords naturally',
        'Keep descriptions concise but informative',
        'Avoid starting with "image of" or "picture of"',
      ],
      tools: ['HTML Editor', 'Image Audit Tool'],
      documentation: ['https://moz.com/learn/seo/alt-text'],
    },
    businessCase: {
      estimatedTrafficIncrease: '5-10%',
      competitorComparison: 'Essential for accessibility compliance',
      roi: '8 minutes work = improved accessibility + SEO',
    },
    quickWin: true,
    category: 'onpage',
    priority: 'medium' as const,
  },
  {
    id: 'rec-3',
    title: 'Fix Missing H1 Tag',
    description: 'This page is missing an H1 heading tag. H1 tags help search engines understand your page structure and main topic.',
    impact: {
      seoScore: 9,
      userExperience: 7,
      conversionPotential: 8,
      implementationEffort: 'low' as const,
      timeToImplement: 2,
    },
    implementation: {
      autoFixAvailable: true,
      codeSnippet: {
        before: '<div class="hero-title">SEO Analysis Dashboard</div>',
        after: '<h1 class="hero-title">SEO Analysis Dashboard</h1>',
        language: 'html',
      },
      stepByStep: [
        'Identify the main heading on your page',
        'Replace the current element with an H1 tag',
        'Ensure only one H1 exists per page',
        'Include your primary keyword naturally',
        'Make it descriptive and compelling',
      ],
      tools: ['HTML Editor', 'SEO Checker'],
      documentation: ['https://moz.com/learn/seo/headings'],
    },
    businessCase: {
      estimatedTrafficIncrease: '10-20%',
      competitorComparison: 'Required for proper page structure',
      roi: '2 minutes work = major SEO improvement',
    },
    quickWin: true,
    category: 'onpage',
    priority: 'high' as const,
  },
  {
    id: 'rec-4',
    title: 'Implement Core Web Vitals Optimization',
    description: 'Your page fails Core Web Vitals metrics. Improve Largest Contentful Paint (LCP) and Cumulative Layout Shift (CLS) for better rankings.',
    impact: {
      seoScore: 9,
      userExperience: 10,
      conversionPotential: 7,
      implementationEffort: 'high' as const,
      timeToImplement: 120,
    },
    implementation: {
      autoFixAvailable: false,
      codeSnippet: {
        before: '<img src="hero-image.jpg" width="800" height="400">',
        after: '<img src="hero-image.jpg" width="800" height="400" loading="lazy" decoding="async" style="aspect-ratio: 2/1;">',
        language: 'html',
      },
      stepByStep: [
        'Audit current Core Web Vitals scores using PageSpeed Insights',
        'Optimize images: compress, resize, and add lazy loading',
        'Minimize JavaScript and CSS bundle sizes',
        'Use resource hints (preload, prefetch) for critical resources',
        'Implement proper image aspect ratios to prevent layout shift',
        'Optimize server response times',
        'Test improvements with Lighthouse',
      ],
      tools: ['PageSpeed Insights', 'Lighthouse', 'WebP Converter', 'Webpack Bundle Analyzer'],
      documentation: ['https://web.dev/vitals/'],
    },
    businessCase: {
      estimatedTrafficIncrease: '20-35%',
      competitorComparison: 'Major Google ranking factor since 2021',
      roi: '2 hours work = significant ranking boost + better UX',
    },
    quickWin: false,
    category: 'performance',
    priority: 'critical' as const,
  },
  {
    id: 'rec-5',
    title: 'Add Structured Data Markup',
    description: 'Implement JSON-LD structured data to help search engines understand your content and enable rich snippets.',
    impact: {
      seoScore: 7,
      userExperience: 5,
      conversionPotential: 8,
      implementationEffort: 'medium' as const,
      timeToImplement: 45,
    },
    implementation: {
      autoFixAvailable: false,
      codeSnippet: {
        before: '<!-- No structured data -->',
        after: `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "SEO Director",
  "url": "https://seo-director.com",
  "description": "Premium SEO analysis and optimization platform",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://seo-director.com/search?q={search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
</script>`,
        language: 'json',
      },
      stepByStep: [
        'Choose appropriate schema.org types for your content',
        'Create JSON-LD structured data markup',
        'Add the script tag to your page head',
        'Validate markup using Google\'s Structured Data Testing Tool',
        'Monitor for rich snippet appearances in search results',
      ],
      tools: ['Schema.org Reference', 'Google Structured Data Testing Tool', 'JSON-LD Generator'],
      documentation: ['https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data'],
    },
    businessCase: {
      estimatedTrafficIncrease: '10-15%',
      competitorComparison: 'Enables rich snippets and enhanced search appearance',
      roi: '45 minutes work = potential rich snippet features',
    },
    quickWin: false,
    category: 'structured',
    priority: 'medium' as const,
  },
  {
    id: 'rec-6',
    title: 'Fix Viewport Meta Tag',
    description: 'Add a viewport meta tag to ensure your site displays correctly on mobile devices. Mobile-friendliness is a ranking factor.',
    impact: {
      seoScore: 8,
      userExperience: 9,
      conversionPotential: 6,
      implementationEffort: 'low' as const,
      timeToImplement: 1,
    },
    implementation: {
      autoFixAvailable: true,
      codeSnippet: {
        before: '<!-- No viewport meta tag -->',
        after: '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        language: 'html',
      },
      stepByStep: [
        'Open your HTML file',
        'Locate the <head> section',
        'Add the viewport meta tag',
        'Test on various mobile devices',
        'Verify mobile-friendly status in Google Search Console',
      ],
      tools: ['HTML Editor', 'Mobile Testing Tool'],
      documentation: ['https://developers.google.com/search/docs/crawling-indexing/mobile/mobile-sites-mobile-first-indexing'],
    },
    businessCase: {
      estimatedTrafficIncrease: '15-25%',
      competitorComparison: 'Essential for mobile-first indexing',
      roi: '1 minute work = mobile compatibility',
    },
    quickWin: true,
    category: 'technical',
    priority: 'high' as const,
  },
];